#!/usr/bin/env python3
"""Generates maps/fixtures.map: a floor with one cube per fixture shader, a caulk-roofed room,
and the three stock shaders used by the baseline screenshots. Run from this directory.

Cube i is centred at x = CUBE0 + i * PITCH, y = 0, standing on the floor (z = 0..64).
The camera for cube i is at (x, -160, 32) looking along +Y (angles "0 90 0").
"""

FIXTURES = [
    "lmfirst", "texfirst", "normalonly", "keywords", "basefactor", "rend2stage",
    "glow", "glowwhite", "glowx4", "envadd", "metalfactor", "roughfactor", "mrmap",
    "fence", "lt128", "nolmadd", "glass", "skypbr", "stageless", "malformed",
]
STOCK = ["base_floor/clangdark", "base_floor/cybergrate2", "gothic_block/blocks10"]
EXTRA = ["skystage", "alphatrans"]  # added after the baseline: a second row at y = EXTRA_Y, so the baseline views hold
EXTRA_Y = 320
CUBE0 = -1024
PITCH = 96
FLOOR = "gothic_block/blocks10"


def box(x1, y1, z1, x2, y2, z2, tex, sides=None):
    """Axis-aligned brush. sides maps face names (-x +x -y +y -z +z) to textures."""
    sides = sides or {}
    def t(face):
        return sides.get(face, tex)  # map files omit the textures/ prefix
    faces = [
        ("-x", (x1, y1, z1), (x1, y1 + 1, z1), (x1, y1, z1 + 1)),
        ("+x", (x2, y2, z2), (x2, y2, z2 + 1), (x2, y2 + 1, z2)),
        ("-y", (x1, y1, z1), (x1, y1, z1 + 1), (x1 + 1, y1, z1)),
        ("+y", (x2, y2, z2), (x2 + 1, y2, z2), (x2, y2, z2 + 1)),
        ("-z", (x1, y1, z1), (x1 + 1, y1, z1), (x1, y1 + 1, z1)),
        ("+z", (x2, y2, z2), (x2, y2 + 1, z2), (x2 + 1, y2, z2)),
    ]
    out = ["{"]
    for face, a, b, c in faces:
        pts = " ".join("( %d %d %d )" % p for p in (a, b, c))
        out.append("%s %s 0 0 0 0.5 0.5 0 0 0" % (pts, t(face)))
    out.append("}")
    return "\n".join(out)


def entity(classname, **keys):
    out = ["{", "\"classname\" \"%s\"" % classname]
    for key, value in keys.items():
        if isinstance(value, tuple):
            value = " ".join("%g" % v for v in value)
        out.append("\"%s\" \"%s\"" % (key, value))
    return "\n".join(out + ["}"]) + "\n"


def lights(names, rx, ry):
    """The integration check's lights (q3-shader-pbr-materials 5.2 and 7.1): a casting sun, a casting spot over
    the fence and the less-than fixture, and a point light by the factor fixtures."""
    x = {name: CUBE0 + i * PITCH for i, name in enumerate(names)}
    fence, metal = x["fixture/fence"], x["fixture/metalfactor"]
    out = entity("light_sun", origin=(fence, 0, 400), angles=(55, 60, 0), intensity=3, _color=(1, 0.95, 0.85))
    out += entity("light_spot", origin=(fence + 48, -160, 220), target="fixture_spot", intensity=400000,
                  radius=700, cone=40, cone_inner=30)
    out += entity("info_null", origin=(fence + 48, 140, 0), targetname="fixture_spot")
    out += entity("light", origin=(metal + 96, -110, 110), intensity=150000, radius=500)
    return out


def main():
    brushes = []
    names = ["fixture/" + f for f in FIXTURES] + STOCK
    xmax = CUBE0 + len(names) * PITCH
    # floor, and a sealing shell of caulk around everything
    brushes.append(box(CUBE0 - 512, -512, -16, xmax + 512, 512, 0, FLOOR))
    for i, name in enumerate(names):
        x = CUBE0 + i * PITCH
        brushes.append(box(x - 32, -32, 0, x + 32, 32, 64, name))
    for i, name in enumerate(EXTRA):
        x = CUBE0 + i * PITCH
        brushes.append(box(x - 32, EXTRA_Y - 32, 0, x + 32, EXTRA_Y + 32, 64, "fixture/" + name))
    # caulk-roofed room: textured walls and ceiling inside, caulk roof outside
    rx, ry = xmax + 128, -192
    wall = FLOOR
    brushes.append(box(rx, ry, 0, rx + 256, ry + 16, 160, wall))
    brushes.append(box(rx, ry + 240, 0, rx + 256, ry + 256, 160, wall))
    brushes.append(box(rx, ry, 0, rx + 16, ry + 256, 160, wall))
    brushes.append(box(rx + 240, ry, 0, rx + 256, ry + 256, 160, wall))
    brushes.append(box(rx, ry, 160, rx + 256, ry + 256, 176, wall, {"+z": "fixture/caulk"}))
    # sky box around the whole map
    lo = (CUBE0 - 528, -528, -32)
    hi = (xmax + 528, 528, 512)
    sky = "fixture/skypbr"
    brushes.append(box(lo[0], lo[1], lo[2], hi[0], lo[1] + 16, hi[2], sky))
    brushes.append(box(lo[0], hi[1] - 16, lo[2], hi[0], hi[1], hi[2], sky))
    brushes.append(box(lo[0], lo[1], lo[2], lo[0] + 16, hi[1], hi[2], sky))
    brushes.append(box(hi[0] - 16, lo[1], lo[2], hi[0], hi[1], hi[2], sky))
    brushes.append(box(lo[0], lo[1], hi[2] - 16, hi[0], hi[1], hi[2], sky))
    brushes.append(box(lo[0], lo[1], lo[2], hi[0], hi[1], lo[2] + 16, sky))

    for path, lit in (("maps/fixtures.map", False), ("maps/fixtures_lit.map", True)):
        with open(path, "w") as f:
            f.write("// generated by make_map.py\n{\n\"classname\" \"worldspawn\"\n")
            for b in brushes:
                f.write(b + "\n")
            f.write("}\n")
            f.write(entity("info_player_deathmatch", origin=(CUBE0, -160, 24), angle=90))
            if lit:
                f.write(lights(names, rx, ry))
    for i, name in enumerate(names):
        print("%-28s camera origin \"%d -160 32\" angles \"0 90 0\"" % (name, CUBE0 + i * PITCH))
    for i, name in enumerate(EXTRA):
        print("%-28s camera origin \"%d %d 32\" angles \"0 90 0\"" % ("fixture/" + name, CUBE0 + i * PITCH, EXTRA_Y - 160))


if __name__ == "__main__":
    main()
